services:

  backend:
    image: nexus-backend:latest
    build: ../nexus_backend
    container_name: nexus_backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: ${MONGO_URI}
      PORT: 3000
    networks:
      - nexus_network

  frontend:
    image: nexus-frontend:latest
    build: ../Nexus_Frontend
    container_name: nexus_frontend
    ports:
      - "8080:80"
    networks:
      - nexus_network

networks:
  nexus_network:
    driver: bridge
