version: "3.8"

services:

  backend:
    image: ${DOCKER_USERNAME}/nexus-backend:latest

    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

    environment:
      MONGO_URI: ${MONGO_URI}

    networks:
      - nexus-network

    ports:
      - "3000:3000"

networks:
  nexus-network:
    external: true