services:

  backend:
    image: ${DOCKER_USER:-omaribarra720}/nexus-backend:latest
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: ${MONGO_URI}
      PORT: 3000
    networks:
      - nexus-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

networks:
  nexus-network:
    driver: overlay